// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MaiaML.Model
{
    public class ModelInput
    {
        [ColumnName("deseise"), LoadColumn(0)]
        public string Deseise { get; set; }


        [ColumnName("symptoms"), LoadColumn(1)]
        public string Symptoms { get; set; }


    }
}
